import { StyleSheet } from 'react-native';
import { wp } from 'zkit-tools';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  linkedRouteLayer: {
    ...StyleSheet.absoluteFillObject,
    elevation: 8,
    zIndex: 8,
  },
  content: {
    paddingHorizontal: wp(16),
  },
  header: {
    paddingBottom: wp(14),
  },
  heroSurface: {
    borderRadius: wp(18),
    borderWidth: wp(1),
    overflow: 'hidden',
    padding: wp(16),
  },
  eyebrow: {
    fontSize: wp(12),
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: wp(16),
    marginTop: 0,
    textTransform: 'uppercase',
  },
  title: {
    fontSize: wp(31),
    fontWeight: '900',
    lineHeight: wp(38),
    marginTop: wp(4),
  },
  subtitle: {
    fontSize: wp(13.5),
    fontWeight: '500',
    lineHeight: wp(22),
    marginTop: wp(10),
  },
  headerPreview: {
    backgroundColor: '#F7F9FC',
    borderColor: '#E5EAF3',
    borderRadius: wp(14),
    borderWidth: wp(1),
    marginTop: wp(16),
    overflow: 'hidden',
  },
  prototypeToolbar: {
    alignItems: 'center',
    borderBottomColor: '#E5EAF3',
    borderBottomWidth: wp(1),
    flexDirection: 'row',
    gap: wp(10),
    height: wp(34),
    paddingHorizontal: wp(12),
  },
  prototypeTrafficLights: {
    flexDirection: 'row',
    gap: wp(5),
  },
  prototypeDot: {
    borderRadius: wp(999),
    height: wp(7),
    width: wp(7),
  },
  prototypeToolbarTrack: {
    backgroundColor: '#E8EDF6',
    borderRadius: wp(999),
    flex: 1,
    height: wp(8),
  },
  prototypeStage: {
    flexDirection: 'row',
    gap: wp(10),
    padding: wp(10),
  },
  prototypeCanvas: {
    borderRadius: wp(12),
    flex: 1,
    minHeight: wp(132),
    overflow: 'hidden',
    padding: wp(12),
  },
  prototypeCanvasGlow: {
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: wp(999),
    height: wp(68),
    position: 'absolute',
    right: wp(-16),
    top: wp(-18),
    width: wp(68),
  },
  prototypeCardPrimary: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: wp(10),
    flexDirection: 'row',
    gap: wp(10),
    minHeight: wp(58),
    paddingHorizontal: wp(10),
  },
  prototypeLogo: {
    borderRadius: wp(8),
    height: wp(34),
    width: wp(34),
  },
  prototypeTextStack: {
    flex: 1,
    gap: wp(8),
  },
  prototypeTitleLine: {
    backgroundColor: '#111827',
    borderRadius: wp(999),
    height: wp(8),
    width: '74%',
  },
  prototypeSubLine: {
    backgroundColor: '#CBD5E1',
    borderRadius: wp(999),
    height: wp(7),
    width: '54%',
  },
  prototypeMetricRow: {
    flexDirection: 'row',
    gap: wp(8),
    marginTop: wp(10),
  },
  prototypeMetric: {
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderColor: 'rgba(255,255,255,0.22)',
    borderRadius: wp(10),
    borderWidth: wp(1),
    flex: 1,
    gap: wp(9),
    minHeight: wp(48),
    padding: wp(9),
  },
  prototypeMetricIcon: {
    borderRadius: wp(999),
    height: wp(9),
    width: wp(22),
  },
  prototypeMetricLine: {
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: wp(999),
    height: wp(7),
    width: '76%',
  },
  prototypeInspector: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E5EAF3',
    borderRadius: wp(12),
    borderWidth: wp(1),
    gap: wp(10),
    justifyContent: 'center',
    paddingHorizontal: wp(10),
    width: wp(96),
  },
  prototypeBarTrack: {
    backgroundColor: '#EEF2F7',
    borderRadius: wp(999),
    height: wp(8),
    overflow: 'hidden',
  },
  prototypeBarFill: {
    borderRadius: wp(999),
    height: '100%',
  },
  prototypeToggleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: wp(7),
    marginTop: wp(2),
  },
  prototypeToggle: {
    backgroundColor: '#13A88B',
    borderRadius: wp(999),
    height: wp(18),
    width: wp(30),
  },
  prototypeToggleLine: {
    backgroundColor: '#CBD5E1',
    borderRadius: wp(999),
    flex: 1,
    height: wp(7),
  },
  headerPreviewFooter: {
    alignItems: 'center',
    borderTopColor: '#E5EAF3',
    borderTopWidth: wp(1),
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: wp(12),
    paddingVertical: wp(10),
  },
  headerPreviewLabel: {
    fontSize: wp(12),
    fontWeight: '800',
    lineHeight: wp(16),
  },
  headerPreviewValue: {
    fontSize: wp(12),
    fontWeight: '700',
    lineHeight: wp(16),
  },
  navWrap: {
    marginHorizontal: wp(-16),
    paddingBottom: wp(6),
  },
  navContent: {
    gap: wp(10),
    paddingHorizontal: wp(16),
  },
  navItem: {
    borderRadius: wp(12),
    borderWidth: wp(1),
    flexDirection: 'row',
    gap: wp(9),
    minHeight: wp(56),
    minWidth: wp(138),
    paddingHorizontal: wp(12),
    paddingVertical: wp(10),
  },
  navItemIcon: {
    alignItems: 'center',
    borderRadius: wp(10),
    height: wp(34),
    justifyContent: 'center',
    width: wp(34),
  },
  navCopy: {
    flex: 1,
    minWidth: 0,
  },
  navTitle: {
    fontSize: wp(13),
    fontWeight: '900',
    lineHeight: wp(17),
  },
  navCaption: {
    fontSize: wp(11),
    fontWeight: '600',
    lineHeight: wp(15),
    marginTop: wp(2),
  },
  section: {
    gap: wp(14),
    paddingTop: wp(24),
    paddingBottom: wp(8),
  },
  sectionHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: wp(12),
  },
  sectionAccent: {
    borderRadius: wp(3),
    height: wp(36),
    marginTop: wp(4),
    width: wp(4),
  },
  sectionCopy: {
    flex: 1,
    minWidth: 0,
  },
  sectionEyebrow: {
    fontSize: wp(11),
    fontWeight: '800',
    letterSpacing: wp(0.5),
    lineHeight: wp(15),
    textTransform: 'uppercase',
  },
  sectionTitle: {
    fontSize: wp(20),
    fontWeight: '900',
    lineHeight: wp(28),
  },
  sectionSubtitle: {
    fontSize: wp(13),
    fontWeight: '400',
    lineHeight: wp(20),
    marginTop: wp(3),
  },
  sectionAction: {
    marginTop: wp(2),
  },
  foundationBand: {
    borderRadius: wp(14),
    borderWidth: wp(1),
    overflow: 'hidden',
  },
  typeSpecimen: {
    paddingHorizontal: wp(16),
    paddingTop: wp(16),
    paddingBottom: wp(12),
  },
  typeHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: wp(10),
  },
  typeLabel: {
    fontSize: wp(12),
    fontWeight: '900',
    lineHeight: wp(16),
    textTransform: 'uppercase',
  },
  typeHeaderLine: {
    backgroundColor: '#E8EEF7',
    borderRadius: wp(999),
    flex: 1,
    height: wp(2),
  },
  typeDisplay: {
    fontSize: wp(23),
    fontWeight: '900',
    lineHeight: wp(31),
    marginTop: wp(12),
  },
  typeSubtitle: {
    fontSize: wp(13.5),
    fontWeight: '600',
    lineHeight: wp(20),
    marginTop: wp(10),
  },
  examplePanelStack: {
    gap: wp(12),
    paddingHorizontal: wp(12),
    paddingBottom: wp(12),
  },
  examplePanel: {
    borderRadius: wp(12),
    borderWidth: wp(1),
    gap: wp(8),
    padding: wp(12),
  },
  spinnerMatrix: {
    alignItems: 'center',
    borderRadius: wp(12),
    borderWidth: wp(1),
    flexDirection: 'row',
    gap: wp(10),
    justifyContent: 'space-between',
    minHeight: wp(58),
    paddingHorizontal: wp(12),
  },
  spinnerExample: {
    alignItems: 'center',
    flex: 1,
    gap: wp(6),
    justifyContent: 'center',
  },
  statusStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(10),
    paddingHorizontal: wp(12),
    paddingTop: wp(2),
    paddingBottom: wp(12),
  },
  statusItem: {
    alignItems: 'center',
    borderRadius: wp(12),
    borderWidth: wp(1),
    flexBasis: '48%',
    flexGrow: 1,
    flexDirection: 'row',
    gap: wp(9),
    minHeight: wp(62),
    paddingHorizontal: wp(10),
    paddingVertical: wp(10),
  },
  statusIcon: {
    alignItems: 'center',
    borderRadius: wp(10),
    height: wp(36),
    justifyContent: 'center',
    width: wp(36),
  },
  statusTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  statusLabel: {
    fontSize: wp(12),
    fontWeight: '800',
    lineHeight: wp(16),
  },
  statusValue: {
    fontSize: wp(13.5),
    fontWeight: '900',
    lineHeight: wp(18),
    marginTop: wp(2),
  },
  actionPanel: {
    borderRadius: wp(12),
    borderWidth: wp(1),
    gap: wp(14),
    padding: wp(14),
  },
  actionPanelHeader: {
    flexDirection: 'row',
    gap: wp(12),
  },
  actionPulse: {
    alignItems: 'center',
    borderRadius: wp(10),
    height: wp(44),
    justifyContent: 'center',
    width: wp(44),
  },
  actionPanelCopy: {
    flex: 1,
    minWidth: 0,
  },
  actionTitle: {
    fontSize: wp(16),
    fontWeight: '900',
    lineHeight: wp(21),
  },
  actionSubtitle: {
    fontSize: wp(13),
    fontWeight: '500',
    lineHeight: wp(19),
    marginTop: wp(3),
  },
  actionDemoStack: {
    gap: wp(14),
  },
  actionDemoGroup: {
    gap: wp(8),
  },
  actionDemoGroupHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: wp(8),
  },
  actionDemoGroupTitle: {
    fontSize: wp(11),
    fontWeight: '900',
    lineHeight: wp(15),
  },
  actionDemoGroupRule: {
    borderRadius: wp(999),
    flex: 1,
    height: wp(1),
  },
  actionDemoRow: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: wp(8),
  },
  actionDemoCell: {
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
  },
  actionDemoIconCell: {
    justifyContent: 'center',
    minWidth: wp(44),
    width: wp(44),
  },
  actionDemoFill: {
    flex: 1.3,
    justifyContent: 'center',
    minWidth: 0,
  },
  fieldStack: {
    gap: wp(20),
  },
  formBlock: {
    gap: wp(10),
  },
  formBlockHeader: {
    gap: wp(2),
    paddingHorizontal: wp(2),
  },
  formBlockTitle: {
    fontSize: wp(14),
    fontWeight: '900',
    lineHeight: wp(19),
  },
  formBlockCaption: {
    fontSize: wp(12),
    fontWeight: '500',
    lineHeight: wp(17),
  },
  formBlockBody: {
    gap: wp(12),
  },
  dualColumnGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(10),
  },
  dualColumnItem: {
    flexBasis: '48%',
    flexGrow: 1,
    minWidth: wp(142),
  },
  textInput: {
    borderRadius: wp(10),
    borderWidth: wp(1),
    fontSize: wp(15),
    minHeight: wp(50),
    paddingHorizontal: wp(14),
    paddingVertical: wp(11),
  },
  switchRow: {
    alignItems: 'center',
    borderRadius: wp(12),
    borderWidth: wp(1),
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: wp(62),
    paddingHorizontal: wp(14),
    paddingVertical: wp(10),
  },
  switchCopy: {
    flex: 1,
    minWidth: 0,
    paddingRight: wp(14),
  },
  switchOptionStack: {
    gap: wp(10),
  },
  switchOption: {
    alignSelf: 'stretch',
    borderRadius: wp(12),
    borderWidth: wp(1),
    minHeight: wp(58),
    paddingHorizontal: wp(14),
    paddingVertical: wp(10),
  },
  switchOptionContent: {
    justifyContent: 'space-between',
    width: '100%',
  },
  controlLabel: {
    fontSize: wp(15),
    fontWeight: '800',
    lineHeight: wp(20),
  },
  controlValue: {
    fontSize: wp(13),
    lineHeight: wp(18),
    marginTop: wp(2),
  },
  spinnerRow: {
    alignItems: 'center',
    borderRadius: wp(12),
    borderWidth: wp(1),
    flexDirection: 'row',
    gap: wp(10),
    minHeight: wp(48),
    paddingHorizontal: wp(14),
  },
  selectionGrid: {
    gap: wp(12),
  },
  selectionBlock: {
    borderRadius: wp(12),
    borderWidth: wp(1),
    gap: wp(12),
    padding: wp(14),
  },
  selectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: wp(10),
  },
  selectionIcon: {
    alignItems: 'center',
    borderRadius: wp(10),
    height: wp(34),
    justifyContent: 'center',
    width: wp(34),
  },
  surfaceGrid: {
    gap: wp(12),
  },
  linkedIntro: {
    alignItems: 'center',
    borderRadius: wp(12),
    borderWidth: wp(1),
    flexDirection: 'row',
    gap: wp(12),
    paddingHorizontal: wp(14),
    paddingVertical: wp(14),
  },
  linkedIntroCopy: {
    flex: 1,
    minWidth: 0,
  },
  linkedIntroText: {
    fontSize: wp(13),
    lineHeight: wp(18),
    marginTop: wp(4),
  },
  sheetContent: {
    gap: wp(14),
    paddingHorizontal: wp(18),
    paddingTop: wp(10),
    paddingBottom: wp(24),
  },
  sheetTitle: {
    fontSize: wp(20),
    fontWeight: '900',
    lineHeight: wp(27),
  },
  sheetSubtitle: {
    fontSize: wp(13),
    fontWeight: '500',
    lineHeight: wp(19),
    marginTop: wp(4),
  },
  sheetGrid: {
    flexDirection: 'row',
    gap: wp(10),
  },
  sheetSwatch: {
    borderRadius: wp(12),
    flex: 1,
    minHeight: wp(74),
    padding: wp(10),
  },
  sheetSwatchLabel: {
    fontSize: wp(12),
    fontWeight: '800',
    lineHeight: wp(16),
  },
  sheetSwatchValue: {
    fontSize: wp(18),
    fontWeight: '900',
    lineHeight: wp(23),
    marginTop: wp(8),
  },
  serviceGrid: {
    gap: wp(10),
  },
  serviceCard: {
    alignItems: 'center',
    borderRadius: wp(12),
    borderWidth: wp(1),
    flexDirection: 'row',
    gap: wp(12),
    minHeight: wp(72),
    paddingHorizontal: wp(14),
    paddingVertical: wp(12),
  },
  serviceIcon: {
    alignItems: 'center',
    borderRadius: wp(10),
    height: wp(40),
    justifyContent: 'center',
    width: wp(40),
  },
  serviceCopy: {
    flex: 1,
    minWidth: 0,
  },
  serviceTitle: {
    fontSize: wp(15),
    fontWeight: '900',
    lineHeight: wp(20),
  },
  serviceSubtitle: {
    fontSize: wp(12),
    fontWeight: '600',
    lineHeight: wp(17),
    marginTop: wp(3),
  },
  toolGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(10),
  },
  toolCard: {
    borderRadius: wp(12),
    borderWidth: wp(1),
    flexBasis: '48%',
    flexGrow: 1,
    minHeight: wp(92),
    padding: wp(12),
  },
  toolIcon: {
    alignItems: 'center',
    borderRadius: wp(10),
    height: wp(32),
    justifyContent: 'center',
    marginBottom: wp(10),
    width: wp(32),
  },
  toolLabel: {
    fontSize: wp(12),
    fontWeight: '700',
    lineHeight: wp(16),
  },
  toolValue: {
    fontSize: wp(15),
    fontWeight: '900',
    lineHeight: wp(20),
    marginTop: wp(3),
  },
  routerGuardPanel: {
    alignItems: 'center',
    borderRadius: wp(12),
    borderWidth: wp(1),
    flexDirection: 'row',
    gap: wp(12),
    marginTop: wp(10),
    minHeight: wp(72),
    paddingHorizontal: wp(14),
    paddingVertical: wp(12),
  },
  routerGuardCopy: {
    flex: 1,
    minWidth: 0,
  },
  paragraph: {
    fontSize: wp(14),
    lineHeight: wp(20),
  },
  fieldTrigger: {
    alignItems: 'center',
    borderRadius: wp(12),
    borderWidth: wp(1),
    flexDirection: 'row',
    gap: wp(12),
    minHeight: wp(64),
    paddingHorizontal: wp(12),
    paddingVertical: wp(10),
  },
  fieldIcon: {
    alignItems: 'center',
    borderRadius: wp(10),
    height: wp(38),
    justifyContent: 'center',
    width: wp(38),
  },
  fieldText: {
    flex: 1,
    minWidth: 0,
  },
  fieldLabel: {
    fontSize: wp(12),
    fontWeight: '800',
    lineHeight: wp(16),
    textTransform: 'uppercase',
  },
  fieldValue: {
    fontSize: wp(16),
    fontWeight: '800',
    lineHeight: wp(21),
    marginTop: wp(3),
  },
  linkedDemoHeader: {
    alignItems: 'center',
    borderBottomWidth: wp(1),
    flexDirection: 'row',
    gap: wp(12),
    paddingBottom: wp(12),
    paddingHorizontal: wp(16),
  },
  linkedBackButton: {
    alignItems: 'center',
    borderRadius: wp(10),
    height: wp(38),
    justifyContent: 'center',
    width: wp(38),
  },
  linkedDemoTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  linkedDemoTitle: {
    fontSize: wp(19),
    fontWeight: '900',
    lineHeight: wp(24),
  },
  linkedDemoSubtitle: {
    fontSize: wp(13),
    lineHeight: wp(18),
    marginTop: wp(2),
  },
  linkedSelectedBadge: {
    alignItems: 'center',
    borderRadius: wp(14),
    justifyContent: 'center',
    minHeight: wp(28),
    minWidth: wp(72),
    paddingHorizontal: wp(10),
  },
  linkedSelectedBadgeText: {
    fontSize: wp(12),
    fontWeight: '900',
    lineHeight: wp(16),
  },
  linkedDemoBody: {
    flex: 1,
    minHeight: 0,
  },
  linkedMenuContent: {
    paddingVertical: wp(8),
  },
  linkedSectionCard: {
    borderRadius: wp(12),
    borderWidth: wp(1),
    overflow: 'hidden',
    paddingHorizontal: wp(18),
    paddingVertical: wp(18),
  },
  linkedSectionHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: wp(12),
  },
  linkedSectionNumber: {
    fontSize: wp(13),
    fontWeight: '900',
    lineHeight: wp(18),
    minWidth: wp(24),
  },
  linkedSectionTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  linkedSectionTitle: {
    fontSize: wp(22),
    fontWeight: '900',
    lineHeight: wp(28),
  },
  linkedSummary: {
    fontSize: wp(14),
    lineHeight: wp(20),
    marginTop: wp(6),
  },
  linkedChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(8),
    marginTop: wp(18),
  },
  linkedChip: {
    borderRadius: wp(14),
    borderWidth: wp(1),
    justifyContent: 'center',
    minHeight: wp(24),
    paddingHorizontal: wp(10),
  },
  linkedChipText: {
    fontSize: wp(12),
    fontWeight: '700',
    lineHeight: wp(16),
  },
  linkedMetricStack: {
    gap: wp(10),
    marginTop: wp(22),
  },
  linkedMetricRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: wp(28),
  },
  linkedMetricLabel: {
    fontSize: wp(13),
    fontWeight: '700',
    lineHeight: wp(18),
  },
  linkedMetricValue: {
    fontSize: wp(14),
    fontWeight: '800',
    lineHeight: wp(19),
  },
});
