import { StyleSheet } from 'react-native';
import { wp } from 'y2kit-tools';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  linkedRouteLayer: {
    ...StyleSheet.absoluteFillObject,
    elevation: 8,
    zIndex: 8,
  },
  content: {
    paddingHorizontal: wp(18),
  },
  header: {
    paddingBottom: wp(18),
  },
  heroSurface: {
    borderRadius: wp(8),
    overflow: 'hidden',
    padding: wp(16),
  },
  headerTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: wp(12),
  },
  brandMark: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: wp(8),
    height: wp(52),
    justifyContent: 'center',
    overflow: 'hidden',
    width: wp(52),
  },
  brandImage: {
    height: wp(46),
    width: wp(46),
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
  },
  eyebrow: {
    fontSize: wp(12),
    fontWeight: '800',
    lineHeight: wp(16),
    textTransform: 'uppercase',
  },
  title: {
    fontSize: wp(34),
    fontWeight: '900',
    lineHeight: wp(40),
    marginTop: wp(2),
  },
  subtitle: {
    fontSize: wp(14),
    fontWeight: '500',
    lineHeight: wp(21),
    marginTop: wp(10),
  },
  headerPreview: {
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderColor: 'rgba(255,255,255,0.28)',
    borderRadius: wp(8),
    borderWidth: wp(1),
    marginTop: wp(16),
    overflow: 'hidden',
  },
  headerPreviewImage: {
    height: wp(102),
    width: '100%',
  },
  headerPreviewFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: wp(12),
    paddingVertical: wp(10),
  },
  headerPreviewLabel: {
    fontSize: wp(12),
    fontWeight: '800',
    lineHeight: wp(16),
  },
  headerPreviewValue: {
    fontSize: wp(12),
    fontWeight: '700',
    lineHeight: wp(16),
  },
  headerStats: {
    flexDirection: 'row',
    gap: wp(8),
    marginTop: wp(14),
  },
  heroStat: {
    flex: 1,
    borderColor: 'rgba(255,255,255,0.28)',
    borderRadius: wp(8),
    borderWidth: wp(1),
    paddingHorizontal: wp(10),
    paddingVertical: wp(10),
  },
  heroStatValue: {
    fontSize: wp(18),
    fontWeight: '900',
    lineHeight: wp(22),
  },
  heroStatLabel: {
    fontSize: wp(11),
    fontWeight: '700',
    lineHeight: wp(15),
    marginTop: wp(3),
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(8),
    marginTop: wp(12),
  },
  metaPill: {
    borderRadius: wp(8),
    paddingHorizontal: wp(10),
    paddingVertical: wp(7),
  },
  metaPillText: {
    fontSize: wp(12),
    fontWeight: '800',
    lineHeight: wp(16),
  },
  navWrap: {
    marginHorizontal: wp(-18),
    paddingBottom: wp(8),
  },
  navContent: {
    gap: wp(10),
    paddingHorizontal: wp(18),
  },
  navItem: {
    borderRadius: wp(8),
    borderWidth: wp(1),
    flexDirection: 'row',
    gap: wp(9),
    minHeight: wp(58),
    minWidth: wp(142),
    paddingHorizontal: wp(12),
    paddingVertical: wp(10),
  },
  navItemIcon: {
    alignItems: 'center',
    borderRadius: wp(8),
    height: wp(34),
    justifyContent: 'center',
    width: wp(34),
  },
  navCopy: {
    flex: 1,
    minWidth: 0,
  },
  navTitle: {
    fontSize: wp(13),
    fontWeight: '900',
    lineHeight: wp(17),
  },
  navCaption: {
    fontSize: wp(11),
    fontWeight: '600',
    lineHeight: wp(15),
    marginTop: wp(2),
  },
  section: {
    gap: wp(14),
    paddingTop: wp(20),
    paddingBottom: wp(8),
  },
  sectionHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: wp(12),
  },
  sectionAccent: {
    borderRadius: wp(3),
    height: wp(38),
    marginTop: wp(3),
    width: wp(5),
  },
  sectionCopy: {
    flex: 1,
    minWidth: 0,
  },
  sectionEyebrow: {
    fontSize: wp(11),
    fontWeight: '900',
    lineHeight: wp(15),
    textTransform: 'uppercase',
  },
  sectionTitle: {
    fontSize: wp(22),
    fontWeight: '900',
    lineHeight: wp(28),
  },
  sectionSubtitle: {
    fontSize: wp(13),
    fontWeight: '500',
    lineHeight: wp(19),
    marginTop: wp(3),
  },
  sectionAction: {
    marginTop: wp(2),
  },
  foundationBand: {
    borderRadius: wp(8),
    borderWidth: wp(1),
    overflow: 'hidden',
  },
  typeSpecimen: {
    paddingHorizontal: wp(16),
    paddingVertical: wp(16),
  },
  typeRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: wp(14),
  },
  typeLabel: {
    fontSize: wp(12),
    fontWeight: '900',
    lineHeight: wp(16),
    minWidth: wp(58),
    textTransform: 'uppercase',
  },
  typeDisplay: {
    flex: 1,
    fontSize: wp(27),
    fontWeight: '900',
    lineHeight: wp(33),
    minWidth: 0,
  },
  typeSubtitle: {
    fontSize: wp(14),
    fontWeight: '600',
    lineHeight: wp(20),
    marginTop: wp(8),
  },
  statusStrip: {
    borderTopWidth: wp(1),
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  statusItem: {
    flexBasis: '50%',
    flexDirection: 'row',
    gap: wp(10),
    minHeight: wp(68),
    paddingHorizontal: wp(14),
    paddingVertical: wp(13),
  },
  statusIcon: {
    alignItems: 'center',
    borderRadius: wp(8),
    height: wp(34),
    justifyContent: 'center',
    width: wp(34),
  },
  statusTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  statusLabel: {
    fontSize: wp(12),
    fontWeight: '700',
    lineHeight: wp(16),
  },
  statusValue: {
    fontSize: wp(14),
    fontWeight: '900',
    lineHeight: wp(19),
    marginTop: wp(2),
  },
  buttonGrid: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(10),
  },
  actionPanel: {
    borderRadius: wp(8),
    borderWidth: wp(1),
    gap: wp(14),
    padding: wp(14),
  },
  actionPanelHeader: {
    flexDirection: 'row',
    gap: wp(12),
  },
  actionPulse: {
    alignItems: 'center',
    borderRadius: wp(8),
    height: wp(44),
    justifyContent: 'center',
    width: wp(44),
  },
  actionPanelCopy: {
    flex: 1,
    minWidth: 0,
  },
  actionTitle: {
    fontSize: wp(16),
    fontWeight: '900',
    lineHeight: wp(21),
  },
  actionSubtitle: {
    fontSize: wp(13),
    fontWeight: '500',
    lineHeight: wp(19),
    marginTop: wp(3),
  },
  fieldStack: {
    gap: wp(12),
  },
  textInput: {
    borderRadius: wp(8),
    borderWidth: wp(1),
    fontSize: wp(16),
    minHeight: wp(52),
    paddingHorizontal: wp(14),
    paddingVertical: wp(11),
  },
  switchRow: {
    alignItems: 'center',
    borderRadius: wp(8),
    borderWidth: wp(1),
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: wp(64),
    paddingHorizontal: wp(14),
    paddingVertical: wp(10),
  },
  switchCopy: {
    flex: 1,
    minWidth: 0,
    paddingRight: wp(14),
  },
  controlLabel: {
    fontSize: wp(15),
    fontWeight: '800',
    lineHeight: wp(20),
  },
  controlValue: {
    fontSize: wp(13),
    lineHeight: wp(18),
    marginTop: wp(2),
  },
  spinnerRow: {
    alignItems: 'center',
    borderRadius: wp(8),
    borderWidth: wp(1),
    flexDirection: 'row',
    gap: wp(10),
    minHeight: wp(48),
    paddingHorizontal: wp(14),
  },
  selectionGrid: {
    gap: wp(12),
  },
  selectionBlock: {
    borderRadius: wp(8),
    borderWidth: wp(1),
    gap: wp(12),
    padding: wp(14),
  },
  selectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: wp(10),
  },
  selectionIcon: {
    alignItems: 'center',
    borderRadius: wp(8),
    height: wp(34),
    justifyContent: 'center',
    width: wp(34),
  },
  accordion: {
    gap: wp(10),
  },
  accordionItem: {
    borderRadius: wp(8),
    borderWidth: wp(1),
    overflow: 'hidden',
  },
  surfaceGrid: {
    gap: wp(12),
  },
  linkedIntro: {
    alignItems: 'center',
    borderRadius: wp(8),
    borderWidth: wp(1),
    flexDirection: 'row',
    gap: wp(12),
    paddingHorizontal: wp(14),
    paddingVertical: wp(14),
  },
  linkedIntroCopy: {
    flex: 1,
    minWidth: 0,
  },
  linkedIntroText: {
    fontSize: wp(13),
    lineHeight: wp(18),
    marginTop: wp(4),
  },
  sheetContent: {
    gap: wp(14),
    paddingHorizontal: wp(18),
    paddingTop: wp(10),
    paddingBottom: wp(24),
  },
  sheetTitle: {
    fontSize: wp(21),
    fontWeight: '900',
    lineHeight: wp(27),
  },
  sheetSubtitle: {
    fontSize: wp(13),
    fontWeight: '500',
    lineHeight: wp(19),
    marginTop: wp(4),
  },
  sheetGrid: {
    flexDirection: 'row',
    gap: wp(10),
  },
  sheetSwatch: {
    borderRadius: wp(8),
    flex: 1,
    minHeight: wp(74),
    padding: wp(10),
  },
  sheetSwatchLabel: {
    fontSize: wp(12),
    fontWeight: '800',
    lineHeight: wp(16),
  },
  sheetSwatchValue: {
    fontSize: wp(18),
    fontWeight: '900',
    lineHeight: wp(23),
    marginTop: wp(8),
  },
  serviceGrid: {
    gap: wp(10),
  },
  serviceCard: {
    alignItems: 'center',
    borderRadius: wp(8),
    borderWidth: wp(1),
    flexDirection: 'row',
    gap: wp(12),
    minHeight: wp(76),
    paddingHorizontal: wp(14),
    paddingVertical: wp(12),
  },
  serviceIcon: {
    alignItems: 'center',
    borderRadius: wp(8),
    height: wp(40),
    justifyContent: 'center',
    width: wp(40),
  },
  serviceCopy: {
    flex: 1,
    minWidth: 0,
  },
  serviceTitle: {
    fontSize: wp(15),
    fontWeight: '900',
    lineHeight: wp(20),
  },
  serviceSubtitle: {
    fontSize: wp(12),
    fontWeight: '600',
    lineHeight: wp(17),
    marginTop: wp(3),
  },
  toolGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(10),
  },
  toolCard: {
    borderRadius: wp(8),
    borderWidth: wp(1),
    flexBasis: '48%',
    flexGrow: 1,
    minHeight: wp(92),
    padding: wp(12),
  },
  toolIcon: {
    alignItems: 'center',
    borderRadius: wp(8),
    height: wp(32),
    justifyContent: 'center',
    marginBottom: wp(10),
    width: wp(32),
  },
  toolLabel: {
    fontSize: wp(12),
    fontWeight: '700',
    lineHeight: wp(16),
  },
  toolValue: {
    fontSize: wp(15),
    fontWeight: '900',
    lineHeight: wp(20),
    marginTop: wp(3),
  },
  routerGuardPanel: {
    alignItems: 'center',
    borderRadius: wp(8),
    borderWidth: wp(1),
    flexDirection: 'row',
    gap: wp(12),
    marginTop: wp(10),
    minHeight: wp(76),
    paddingHorizontal: wp(14),
    paddingVertical: wp(12),
  },
  routerGuardCopy: {
    flex: 1,
    minWidth: 0,
  },
  paragraph: {
    fontSize: wp(14),
    lineHeight: wp(20),
  },
  fieldTrigger: {
    alignItems: 'center',
    borderRadius: wp(8),
    borderWidth: wp(1),
    flexDirection: 'row',
    gap: wp(12),
    minHeight: wp(66),
    paddingHorizontal: wp(12),
    paddingVertical: wp(10),
  },
  fieldIcon: {
    alignItems: 'center',
    borderRadius: wp(8),
    height: wp(38),
    justifyContent: 'center',
    width: wp(38),
  },
  fieldText: {
    flex: 1,
    minWidth: 0,
  },
  fieldLabel: {
    fontSize: wp(12),
    fontWeight: '800',
    lineHeight: wp(16),
    textTransform: 'uppercase',
  },
  fieldValue: {
    fontSize: wp(16),
    fontWeight: '800',
    lineHeight: wp(21),
    marginTop: wp(3),
  },
  linkedDemoHeader: {
    alignItems: 'center',
    borderBottomWidth: wp(1),
    flexDirection: 'row',
    gap: wp(12),
    paddingBottom: wp(12),
    paddingHorizontal: wp(16),
  },
  linkedBackButton: {
    alignItems: 'center',
    borderRadius: wp(8),
    height: wp(38),
    justifyContent: 'center',
    width: wp(38),
  },
  linkedDemoTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  linkedDemoTitle: {
    fontSize: wp(19),
    fontWeight: '900',
    lineHeight: wp(24),
  },
  linkedDemoSubtitle: {
    fontSize: wp(13),
    lineHeight: wp(18),
    marginTop: wp(2),
  },
  linkedSelectedBadge: {
    alignItems: 'center',
    borderRadius: wp(8),
    justifyContent: 'center',
    minHeight: wp(28),
    minWidth: wp(72),
    paddingHorizontal: wp(10),
  },
  linkedSelectedBadgeText: {
    fontSize: wp(12),
    fontWeight: '900',
    lineHeight: wp(16),
  },
  linkedDemoBody: {
    flex: 1,
    minHeight: 0,
  },
  linkedMenuContent: {
    paddingVertical: wp(8),
  },
  linkedSectionCard: {
    borderRadius: wp(8),
    borderWidth: wp(1),
    overflow: 'hidden',
    paddingHorizontal: wp(18),
    paddingVertical: wp(18),
  },
  linkedSectionHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: wp(12),
  },
  linkedSectionNumber: {
    fontSize: wp(13),
    fontWeight: '900',
    lineHeight: wp(18),
    minWidth: wp(24),
  },
  linkedSectionTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  linkedSectionTitle: {
    fontSize: wp(22),
    fontWeight: '900',
    lineHeight: wp(28),
  },
  linkedSummary: {
    fontSize: wp(14),
    lineHeight: wp(20),
    marginTop: wp(6),
  },
  linkedChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(8),
    marginTop: wp(18),
  },
  linkedChip: {
    borderRadius: wp(8),
    borderWidth: wp(1),
    justifyContent: 'center',
    minHeight: wp(24),
    paddingHorizontal: wp(10),
  },
  linkedChipText: {
    fontSize: wp(12),
    fontWeight: '700',
    lineHeight: wp(16),
  },
  linkedMetricStack: {
    gap: wp(10),
    marginTop: wp(22),
  },
  linkedMetricRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: wp(28),
  },
  linkedMetricLabel: {
    fontSize: wp(13),
    fontWeight: '700',
    lineHeight: wp(18),
  },
  linkedMetricValue: {
    fontSize: wp(14),
    fontWeight: '800',
    lineHeight: wp(19),
  },
});
